sudo: required
services:
  - docker

before_install:
  - docker build -t ken/react-docker-test -f Dockerfile.dev .

script:
  - docker run ken/react-docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker-test"
  env: "ReactDockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-905141291592"
  bucket_path: "react-docker-test"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"